# Generated by Django 4.1.2 on 2022-10-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletime',
            name='create_at',
        ),
        migrations.AddField(
            model_name='cycletime',
            name='create_at_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cycletime',
            name='create_at_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
