# Generated by Django 4.1.2 on 2022-10-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_cycletime_create_at_cycletime_create_at_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycletime',
        ),
    ]
