# Generated by Django 4.1.2 on 2022-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_cycletime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycletime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(max_length=50)),
                ('create_at_date', models.DateField(auto_now=True, null=True)),
                ('create_at_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
