# Generated by Django 4.1.2 on 2022-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cycletime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orActual', models.FloatField()),
                ('orTarget', models.FloatField()),
                ('accualOutput', models.IntegerField()),
                ('targetOutput', models.IntegerField()),
                ('outputDiff', models.IntegerField()),
                ('stdTarget', models.FloatField()),
                ('stdActual', models.FloatField()),
                ('lastpast', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('actual', models.CharField(max_length=50)),
                ('orShift', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
