# Generated by Django 4.1.2 on 2022-11-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_track_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='color',
            field=models.CharField(max_length=500),
        ),
    ]
