# Generated by Django 4.1.2 on 2022-11-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_track_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='shift',
            field=models.CharField(default='day', max_length=10),
        ),
    ]
