# Generated by Django 4.1.2 on 2022-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_track_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
