# Generated by Django 5.0.6 on 2024-05-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletime',
            name='create_at_time',
            field=models.TimeField(null=True),
        ),
    ]
