# Generated by Django 4.1.2 on 2022-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
