# Generated by Django 4.1.2 on 2022-12-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0002_loss_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loss',
        ),
    ]
