# Generated by Django 4.1.2 on 2022-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
