# Generated by Django 4.1.2 on 2022-12-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0005_alter_loss_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='create_at_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
