# Generated by Django 4.1.2 on 2022-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0006_loss_create_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_time',
            field=models.TimeField(null=True),
        ),
    ]
