# Generated by Django 4.1.2 on 2022-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0007_alter_loss_create_at_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loss',
            old_name='date',
            new_name='create_at_date',
        ),
    ]
