# Generated by Django 4.1.2 on 2022-12-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0008_rename_date_loss_create_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_date',
            field=models.DateField(null=True),
        ),
    ]
