# Generated by Django 4.1.2 on 2022-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0009_alter_loss_create_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_date',
            field=models.DateField(choices=[('7:35-8:30', '7:30'), ('8:30-9:30', '8:30'), ('9:40-10:30', '9:50'), ('10:30-11:15', '11:00'), ('12:15-13:30', '12:30'), ('13:30-14:30', '13:31'), ('14:40-15:30', '14:50'), ('15:30-16:30', '15:40'), ('16:50-17:50', '17:00'), ('17:50-18:40', '18:30'), ('18:50-19:20', '18:51')], null=True),
        ),
    ]
