# Generated by Django 4.1.2 on 2022-12-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0010_alter_loss_create_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_date',
            field=models.DateField(choices=[('7:30', '7:35-8:30'), ('8:30', '8:30-9:30'), ('9:50', '9:40-10:30'), ('11:00', '10:30-11:15'), ('12:30', '12:15-13:30'), ('13:31', '13:30-14:30'), ('14:50', '14:40-15:30'), ('15:40', '15:30-16:30'), ('17:00', '16:50-17:50'), ('18:30', '17:50-18:40'), ('18:51', '18:50-19:20')], null=True),
        ),
        migrations.AlterField(
            model_name='loss',
            name='lossType',
            field=models.CharField(choices=[('part_supply', 'Part Supply'), ('defect', 'Defect'), ('breakdown', 'Breakdown'), ('short_stop', 'Short Stop'), ('changing', 'Changing/Model Change')], max_length=40),
        ),
    ]
