# Generated by Django 4.1.2 on 2022-12-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0011_alter_loss_create_at_date_alter_loss_losstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loss',
            name='create_at_time',
            field=models.TimeField(choices=[('7:30', '7:35-8:30'), ('8:30', '8:30-9:30'), ('9:50', '9:40-10:30'), ('11:00', '10:30-11:15'), ('12:30', '12:15-13:30'), ('13:31', '13:30-14:30'), ('14:50', '14:40-15:30'), ('15:40', '15:30-16:30'), ('17:00', '16:50-17:50'), ('18:30', '17:50-18:40'), ('18:51', '18:50-19:20'), ('19:50', '19:35-20:30'), ('20:40', '20:30-21:30'), ('21:50', '21:40-22:30'), ('22:40', '22:30-23:30'), ('00:30', '00:20-01:30'), ('01:40', '01:30-02:30'), ('02:51', '02:50-03:30'), ('03:40', '03:30-04:30'), ('05:00', '04:50-05:50'), ('06:00', '05:50-06:40'), ('07:00', '06:40-07:20')], null=True),
        ),
    ]
