# Generated by Django 4.1.2 on 2022-12-21 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0020_alter_loss_create_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
    ]
