# Generated by Django 4.1.2 on 2022-12-22 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0022_alter_loss_create_at_date_alter_loss_create_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='create_at_time',
            field=models.TimeField(choices=[(datetime.time(7, 40), '7:35-8:30'), (datetime.time(8, 40), '8:30-9:30'), (datetime.time(9, 50), '9:40-10:30'), (datetime.time(11, 0), '10:30-11:15'), (datetime.time(12, 30), '12:15-13:30'), (datetime.time(13, 31), '13:30-14:30'), (datetime.time(14, 50), '14:40-15:30'), (datetime.time(15, 40), '15:30-16:30'), (datetime.time(17, 0), '16:50-17:50'), (datetime.time(18, 30), '17:50-18:40'), (datetime.time(18, 51), '18:50-19:20'), (datetime.time(19, 50), '19:35-20:30'), (datetime.time(20, 40), '20:30-21:30'), (datetime.time(21, 50), '21:40-22:30'), (datetime.time(22, 40), '22:30-23:30'), (datetime.time(0, 30), '00:20-01:30'), (datetime.time(1, 40), '01:30-02:30'), (datetime.time(3, 20), '02:50-03:30'), (datetime.time(3, 40), '03:30-04:30'), (datetime.time(5, 0), '04:50-05:50'), (datetime.time(6, 0), '05:50-06:40'), (datetime.time(7, 0), '06:40-07:20')], null=True, verbose_name='Shift'),
        ),
    ]
