# Generated by Django 4.1.2 on 2023-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lossreport', '0023_alter_loss_create_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='ABCType',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
    ]
